apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "fastapi.fullname" . }}-pv
spec:
  capacity:
    storage: {{- if .Values.persistence }}
               {{ .Values.persistence.size }}
             {{- end }}    

  accessModes:
    - {{- if .Values.persistence }}
        {{ .Values.persistence.accessMode }}
      {{- end }}

  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.persistence.storageClass }}
  hostPath:   # ← à adapter selon ton type de volume
    path: {{ include "fastapi.fullname" . }}

