apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "fastapi.fullname" . }}-pv
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.persistence.storageClass }}
  hostPath:   # ← à adapter selon ton type de volume
    path: {{ include "fastapi.fullname" . }}

