apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "fastapi.fullname" . }}-pv
spec:
  capacity:
    storage: {{- if .Values.persistence }}
               {{ .Values.persistence.size |  default "100Mi" }}
             {{- end }}    

  accessModes:
    - {{- if .Values.persistence }}
        {{ .Values.persistence.accessMode |  default "ReadWriteOnce" }}
      {{- end }}

  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{- if .Values.persistence }} 
                       {{ .Values.persistence.storageClass }}
                    {{- end }}   
  hostPath:   # ← à adapter selon ton type de volume
    path: {{ include "fastapi.fullname" . }}

