apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "fastapi.fullname" . }}-pvc
spec:
  accessModes:
    -{{- if .Values.persistence }}
        {{ .Values.persistence.accessMode |  default "ReadWriteOnce" }}
     {{- end }}   
  resources:
    requests:
      storage:{{- if .Values.persistence }} 
                 {{ .Values.persistence.size }}
              {{- end }}

  storageClassName:{{- if .Values.persistence }}
                      {{ .Values.persistence.storageClass  | default "standard" }}
                   {{- end }}     

